# -*- coding: utf-8 -*-
"""Web Scraping - IMDB

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ux2yb3pEbfRu339k9YY9bxA2ElTD49wS
"""

import requests,openpyxl
from bs4 import BeautifulSoup as bs
import pandas as pd
headers = {'Accept-Language': 'en-US,en;q=0.5'}

excel = openpyxl.Workbook()
sheet = excel.active
sheet.title = 'Top Rated TV Series'

sheet.append(['Movie Rank','Movie Name','Year Of Release','IMDB Rating'])

"""##Top 250 TV series from IMDB all time list"""

source = requests.get('https://www.imdb.com/chart/toptv/',headers = headers)
soup = bs(source.text,'html.parser')
print(soup.prettify())

series = soup.find('tbody',class_ = "lister-list").find_all('tr')
print(len(series))

movie_name = []
year_ = []
rating_ = []
rank_=[]

for s in series:

  name = s.find('td',class_="titleColumn").a.text
  movie_name.append(name)
  rank = s.find('td',class_="titleColumn").get_text(strip=True).split('.')[0]
  rank_.append(rank)
  year = s.find('td',class_="titleColumn").span.text.strip('()')
  year_.append(year)
  rating = s.find('td',class_="ratingColumn imdbRating").strong.text
  rating_.append(rating)
  print(rank,name,year,rating)
  sheet.append([rank, name, year, rating])

excel.save('IMDB TV Series.xlsx')

a = {'Movie Rank': rank_,'Movie Name' : movie_name,'Year Of Release' : year_,'IMDB Rating' : rating_}
Series = pd.DataFrame.from_dict(a,orient='index').reset_index(drop = True).transpose()
Series.columns=['Series Rank','Series Name','Year Of Release','IMDB Rating']
Series.head(10)