# -*- coding: utf-8 -*-
"""Web Scraping - IMDB

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ux2yb3pEbfRu339k9YY9bxA2ElTD49wS
"""

import requests,openpyxl
from bs4 import BeautifulSoup as bs

headers = {'Accept-Language': 'en-US,en;q=0.5'}

excel = openpyxl.Workbook()
sheet = excel.active
sheet.title = 'Top Rated TV Series'

sheet.append(['Movie Rank','Movie Name','Year Of Release','IMDB Rating'])

"""##Top 250 TV series from IMDB all time list"""

source = requests.get('https://www.imdb.com/chart/toptv/',headers = headers)
soup = bs(source.text,'html.parser')
print(soup.prettify())

series = soup.find('tbody',class_ = "lister-list").find_all('tr')
print(len(series))

for s in series:

  name = s.find('td',class_="titleColumn").a.text
  rank = s.find('td',class_="titleColumn").get_text(strip=True).split('.')[0]
  year = s.find('td',class_="titleColumn").span.text.strip('()')
  rating = s.find('td',class_="ratingColumn imdbRating").strong.text
  print(rank,name,year,rating)
  sheet.append([rank, name, year, rating])

excel.save('IMDB TV Series.xlsx')